# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_scope.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScopeViewer(object):
    def setupUi(self, ScopeViewer):
        ScopeViewer.setObjectName("ScopeViewer")
        ScopeViewer.resize(400, 300)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ScopeViewer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushbutton_connect = QtWidgets.QPushButton(ScopeViewer)
        self.pushbutton_connect.setObjectName("pushbutton_connect")
        self.horizontalLayout.addWidget(self.pushbutton_connect)
        self.pushbutton_start = QtWidgets.QPushButton(ScopeViewer)
        self.pushbutton_start.setObjectName("pushbutton_start")
        self.horizontalLayout.addWidget(self.pushbutton_start)
        self.pushbutton_stop = QtWidgets.QPushButton(ScopeViewer)
        self.pushbutton_stop.setObjectName("pushbutton_stop")
        self.horizontalLayout.addWidget(self.pushbutton_stop)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget_plot = GraphicsLayoutWidget(ScopeViewer)
        self.widget_plot.setObjectName("widget_plot")
        self.verticalLayout.addWidget(self.widget_plot)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(ScopeViewer)
        QtCore.QMetaObject.connectSlotsByName(ScopeViewer)

    def retranslateUi(self, ScopeViewer):
        _translate = QtCore.QCoreApplication.translate
        ScopeViewer.setWindowTitle(_translate("ScopeViewer", "Form"))
        self.pushbutton_connect.setText(_translate("ScopeViewer", "Connect"))
        self.pushbutton_start.setText(_translate("ScopeViewer", "Start"))
        self.pushbutton_stop.setText(_translate("ScopeViewer", "Stop"))
from pyqtgraph import GraphicsLayoutWidget
